oss:
    type: local
    root_directory: ./data
    aliyun:
        access_key_id: xxx
        access_key_secret: xxx
        bucket_name: xxx
        endpoint: https://oss-cn-beijing.aliyuncs.com
    minio:
        access_key: minioadmin
        bucket_name: kratos-admin
        endpoint: http://127.0.0.1:9000
        secret_key: minioadmin
        use_ssl: false
    s3:
        access_key: minioadmin
        bucket_name: kratos-admin
        endpoint: http://127.0.0.1:9000
        force_path_style: true
        region: us-east-1
        secret_key: minioadmin
        use_ssl: false
    upload_security:
        command: clamdscan
        enabled: false
