package main

import (
	"fmt"
	"strconv"

	cmdutils "github.com/liujitcn/kratos-kit/cmd/internal/utils"
	kitutils "github.com/liujitcn/kratos-kit/utils"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/descriptorpb"
)

const (
	jsonPackage    = protogen.GoImportPath("encoding/json")
	contextPackage = protogen.GoImportPath("context")
	mcpPackage     = protogen.GoImportPath("github.com/modelcontextprotocol/go-sdk/mcp")
)

const deprecationComment = "// Deprecated: Do not use."

// generateMCPToolFile 生成 MCP Tool 文件。
func generateMCPToolFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if len(file.Services) == 0 {
		return nil
	}

	filename := file.GeneratedFilenamePrefix + "_mcp_tool.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-mcp-tool.")
	g.P("// versions:")
	g.P(fmt.Sprintf("// - protoc-gen-go-mcp-tool %s", release))
	g.P("// - protoc                  ", cmdutils.ProtocVersion(gen))
	if file.Proto.GetOptions().GetDeprecated() {
		g.P("// ", file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", file.Desc.Path())
	}
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	generateMCPToolFileContent(g, file)

	content, err := g.Content()
	if err != nil {
		panic(err)
	}
	content, err = cmdutils.FormatGeneratedContent(filename, content)
	if err != nil {
		panic(err)
	}

	g.Skip()
	cleanFile := gen.NewGeneratedFile(filename, "")
	_, _ = cleanFile.Write(content)
	return cleanFile
}

// generateMCPToolFileContent 生成 MCP Tool 文件主体内容。
func generateMCPToolFileContent(g *protogen.GeneratedFile, file *protogen.File) {
	for _, service := range file.Services {
		generateServiceMCPTools(g, file, service)
	}
}

// generateServiceMCPTools 为一个 proto service 生成 MCP Tool 注册函数与各 RPC Tool 注册函数。
func generateServiceMCPTools(g *protogen.GeneratedFile, file *protogen.File, service *protogen.Service) {
	if service.Desc.Options().(*descriptorpb.ServiceOptions).GetDeprecated() {
		g.P(deprecationComment)
	}

	serviceName := service.GoName
	serverName := cmdutils.Unexport(serviceName) + "Server"
	g.P(formatTypeComment("Register"+serviceName+"MCPTools", cmdutils.NormalizeCommentText(service.Comments.Leading)))
	g.P("func Register", serviceName, "MCPTools(mcpServer *", g.QualifiedGoIdent(mcpPackage.Ident("Server")), ", ", serverName, " ", service.GoName, "Server) {")
	for _, method := range service.Methods {
		if !cmdutils.IsUnaryMethod(method) {
			continue
		}
		g.P("Register", serviceName, method.GoName, "MCPTool(mcpServer, ", serverName, ")")
	}
	g.P("}")
	g.P()

	for _, method := range service.Methods {
		if !cmdutils.IsUnaryMethod(method) {
			continue
		}
		generateMethodMCPTool(g, file, service, method)
	}
}

// generateMethodMCPTool 为一个一元 RPC 生成 MCP Tool 注册函数。
func generateMethodMCPTool(g *protogen.GeneratedFile, file *protogen.File, service *protogen.Service, method *protogen.Method) {
	toolName := kitutils.ToolNameFromRPCPath("/" + string(service.Desc.FullName()) + "/" + string(method.Desc.Name()))
	description := cmdutils.ToolDescription(service, method)
	serverName := cmdutils.Unexport(service.GoName) + "Server"
	requestType := g.QualifiedGoIdent(method.Input.GoIdent)
	responseType := g.QualifiedGoIdent(method.Output.GoIdent)
	inputType := "*" + requestType
	outputType := "*" + responseType
	if messageHasRecursiveReference(method.Input) {
		inputType = "any"
	}
	if messageHasRecursiveReference(method.Output) {
		outputType = "any"
	}

	if method.Desc.Options().(*descriptorpb.MethodOptions).GetDeprecated() {
		g.P(deprecationComment)
	}
	g.P(formatMethodComment("Register"+service.GoName+method.GoName+"MCPTool", cmdutils.NormalizeCommentText(method.Comments.Leading)))
	g.P("func Register", service.GoName, method.GoName, "MCPTool(mcpServer *", g.QualifiedGoIdent(mcpPackage.Ident("Server")), ", ", serverName, " ", service.GoName, "Server) {")
	g.P(g.QualifiedGoIdent(mcpPackage.Ident("AddTool")), "[", inputType, ", ", outputType, "](")
	g.P("mcpServer,")
	g.P("&", g.QualifiedGoIdent(mcpPackage.Ident("Tool")), "{")
	g.P("Name: ", strconv.Quote(toolName), ",")
	g.P("Description: ", strconv.Quote(description), ",")
	g.P("},")
	g.P("func(ctx ", g.QualifiedGoIdent(contextPackage.Ident("Context")), ", request *", g.QualifiedGoIdent(mcpPackage.Ident("CallToolRequest")), ", input ", inputType, ") (*", g.QualifiedGoIdent(mcpPackage.Ident("CallToolResult")), ", ", outputType, ", error) {")
	if inputType == "any" {
		g.P("req := &", requestType, "{}")
		g.P("if input != nil {")
		g.P("inputBytes, err := ", g.QualifiedGoIdent(jsonPackage.Ident("Marshal")), "(input)")
		g.P("if err != nil {")
		g.P("return nil, nil, err")
		g.P("}")
		g.P("if err = ", g.QualifiedGoIdent(jsonPackage.Ident("Unmarshal")), "(inputBytes, req); err != nil {")
		g.P("return nil, nil, err")
		g.P("}")
		g.P("}")
	} else {
		g.P("if input == nil {")
		g.P("input = &", requestType, "{}")
		g.P("}")
	}
	requestValue := "input"
	if inputType == "any" {
		requestValue = "req"
	}
	g.P("reply, err := ", serverName, ".", method.GoName, "(ctx, ", requestValue, ")")
	g.P("if err != nil {")
	g.P("return nil, nil, err")
	g.P("}")
	g.P("return nil, reply, nil")
	g.P("},")
	g.P(")")
	g.P("}")
	g.P()
}

// messageHasRecursiveReference 判断 message 依赖图中是否存在递归引用。
func messageHasRecursiveReference(message *protogen.Message) bool {
	if message == nil {
		return false
	}
	visiting := make(map[protogen.GoIdent]bool)
	visited := make(map[protogen.GoIdent]bool)
	return messageHasRecursiveReferenceInStack(message, visiting, visited)
}

// messageHasRecursiveReferenceInStack 深度遍历 message 字段，发现回到当前访问栈时视为递归。
func messageHasRecursiveReferenceInStack(message *protogen.Message, visiting, visited map[protogen.GoIdent]bool) bool {
	if message == nil {
		return false
	}
	ident := message.GoIdent
	if visiting[ident] {
		return true
	}
	if visited[ident] {
		return false
	}
	visiting[ident] = true
	defer delete(visiting, ident)

	for _, field := range message.Fields {
		if field.Message == nil {
			continue
		}
		if messageHasRecursiveReferenceInStack(field.Message, visiting, visited) {
			return true
		}
	}

	visited[ident] = true
	return false
}

// formatTypeComment 生成类型或构造函数注释，统一采用“名称 描述”格式。
func formatTypeComment(name, comment string) string {
	if comment == "" {
		return "// " + name
	}
	return cmdutils.FormatToolActionComment(name, comment, "注册", "MCP Tool")
}

// formatMethodComment 生成方法注释，保持“// 方法名 描述”的输出样式。
func formatMethodComment(name, comment string) string {
	if comment == "" {
		return "// " + name
	}
	return cmdutils.FormatToolActionComment(name, comment, "注册", "MCP Tool")
}
