package main

import (
	"fmt"
	"go/format"
	"go/token"
	"path/filepath"
	"strings"
)

// generateCatalogGoSource 生成只负责嵌入项目文档目录的 Go 源码。
func generateCatalogGoSource(goOutputPath, catalogOutputPath string) ([]byte, error) {
	goDirectory, err := filepath.Abs(filepath.Dir(goOutputPath))
	if err != nil {
		return nil, fmt.Errorf("解析 Go 生成目录: %w", err)
	}
	var catalogPath string
	catalogPath, err = filepath.Abs(catalogOutputPath)
	if err != nil {
		return nil, fmt.Errorf("解析项目文档目录路径: %w", err)
	}
	var embedPath string
	embedPath, err = filepath.Rel(goDirectory, catalogPath)
	if err != nil {
		return nil, fmt.Errorf("计算项目文档嵌入路径: %w", err)
	}
	embedPath = filepath.ToSlash(embedPath)
	if embedPath == "." || strings.HasPrefix(embedPath, "../") {
		return nil, fmt.Errorf("项目文档目录必须位于 Go 生成文件目录内: %s", catalogOutputPath)
	}
	packageName := filepath.Base(goDirectory)
	if !token.IsIdentifier(packageName) {
		return nil, fmt.Errorf("Go 生成目录名不是有效包名: %s", packageName)
	}

	source := fmt.Sprintf(`// Code generated by project-docs. DO NOT EDIT.

// Package %[1]s 保存构建期生成的项目文档目录。
package %[1]s

import _ "embed"

// DocsData 是构建期生成的项目文档目录。
//
//go:embed %[2]q
var DocsData []byte
`, packageName, embedPath)
	var formattedSource []byte
	formattedSource, err = format.Source([]byte(source))
	if err != nil {
		return nil, fmt.Errorf("格式化 Go 嵌入文件: %w", err)
	}
	return formattedSource, nil
}
