package main

import (
	"fmt"
	"go/format"
	"go/token"
	"path"
	"path/filepath"
	"strings"
)

// generateCatalogGoSource 生成嵌入默认语言和多语言项目文档目录的 Go 源码。
func generateCatalogGoSource(goOutputPath, catalogOutputPath string) ([]byte, error) {
	goDirectory, err := filepath.Abs(filepath.Dir(goOutputPath))
	if err != nil {
		return nil, fmt.Errorf("解析 Go 生成目录: %w", err)
	}
	var catalogPath string
	catalogPath, err = filepath.Abs(catalogOutputPath)
	if err != nil {
		return nil, fmt.Errorf("解析项目文档目录路径: %w", err)
	}
	var embedPath string
	embedPath, err = filepath.Rel(goDirectory, catalogPath)
	if err != nil {
		return nil, fmt.Errorf("计算项目文档嵌入路径: %w", err)
	}
	embedPath = filepath.ToSlash(embedPath)
	if embedPath == "." || strings.HasPrefix(embedPath, "../") {
		return nil, fmt.Errorf("项目文档目录必须位于 Go 生成文件目录内: %s", catalogOutputPath)
	}
	packageName := filepath.Base(goDirectory)
	if !token.IsIdentifier(packageName) {
		return nil, fmt.Errorf("Go 生成目录名不是有效包名: %s", packageName)
	}

	embedDirectory := filepath.ToSlash(filepath.Dir(embedPath))
	embedPattern := path.Join(embedDirectory, "docs*.json")
	source := fmt.Sprintf(`// Code generated by project-docs. DO NOT EDIT.

package %[1]s

import "embed"

// DocsData 是构建期生成的默认语言项目文档目录。
//
//go:embed %[2]q
var DocsData []byte

// DocsFS 包含默认语言和各语言后缀的项目文档目录。
//
//go:embed %[3]q
var DocsFS embed.FS
`, packageName, embedPath, embedPattern)
	var formattedSource []byte
	formattedSource, err = format.Source([]byte(source))
	if err != nil {
		return nil, fmt.Errorf("格式化 Go 嵌入文件: %w", err)
	}
	return formattedSource, nil
}
