[request_definition]
r = tenant, sub, obj, act

[policy_definition]
p = tenant, sub_rule, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.tenant == p.tenant && eval(p.sub_rule) && r.obj == p.obj && r.act == p.act
