[request_definition]
r = tenant, sub, obj, act, dom

[policy_definition]
p = tenant, sub, obj, act, dom

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.tenant == p.tenant && r.sub == p.sub && r.dom == p.dom && r.obj == p.obj && r.act == p.act
