[request_definition]
r = tenant, sub, obj, act, dom

[policy_definition]
p = tenant, sub, obj, act, dom

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.tenant == p.tenant && r.sub == p.sub && keyMatch2(r.obj, p.obj) && (regexMatch(r.act, p.act) || p.act == 'ANY') && (keyMatch(r.dom, p.dom) || p.dom == '*')
