package main

import (
	"os"
	"path/filepath"
	"text/template"

	pgs "github.com/lyft/protoc-gen-star/v2"
	pgsgo "github.com/lyft/protoc-gen-star/v2/lang/go"
)

// Redactor returns the implementation of the protoc-gen-redact plugin
// to generate redaction file
func Redactor() pgs.Module { return &Module{ModuleBase: &pgs.ModuleBase{}} }

// Module implements the pgs.Module interface for protoc-gen-redact plugin
type Module struct {
	*pgs.ModuleBase
	ctx  pgsgo.Context
	tmpl *template.Template
}

// Name returns the name of this protoc-gen-star module
func (*Module) Name() string { return "redactor" }

// InitContext satisfies the pgs.Module interface and helps build the module
func (m *Module) InitContext(c pgs.BuildContext) {
	// Add panic recovery for initialization
	defer func() {
		if r := recover(); r != nil {
			m.Failf("Panic during module initialization: %v", r)
		}
	}()

	m.ModuleBase.InitContext(c)
	m.ctx = pgsgo.InitContext(c.Parameters())

	// Validate context
	if m.ctx == nil {
		m.Fail("Failed to initialize Go context")
		return
	}

	// Check for custom template file parameter
	templateFile := c.Parameters().Str("template_file")

	tpl := template.New("redact").Funcs(map[string]interface{}{
		"package": m.ctx.PackageName,
		"name":    m.ctx.Name,
	})

	var parsedTpl *template.Template
	var err error

	if templateFile != "" {
		// Load template from external file
		m.Debug("Loading template from file: " + templateFile)
		parsedTpl, err = m.loadTemplateFromFile(tpl, templateFile)
		if err != nil {
			m.Failf("Failed to load template from file %s: %v", templateFile, err)
			return
		}
		m.Debug("Successfully loaded external template")
	} else {
		// Use embedded template
		m.Debug("Using embedded template")
		parsedTpl, err = tpl.Parse(redactTpl)
		if err != nil {
			m.Failf("Failed to parse embedded template: %v", err)
			return
		}
	}

	m.tmpl = parsedTpl
	m.Debug("Module initialized successfully")
}

// Execute satisfies the pgs.Module interface & generates the redactor file
// for the targeted files
func (m *Module) Execute(targets map[string]pgs.File, _ map[string]pgs.Package) []pgs.Artifact {
	// process all the target files
	for _, file := range targets {
		m.Process(file)
	}
	return m.Artifacts()
}

// loadTemplateFromFile loads a template from an external file
func (m *Module) loadTemplateFromFile(tpl *template.Template, templatePath string) (*template.Template, error) {
	// Validate the file path
	if templatePath == "" {
		return nil, ErrorContext{
			Location: "template_file parameter",
			Reason:   "template file path is empty",
		}
	}

	// Resolve absolute path
	absPath, err := filepath.Abs(templatePath)
	if err != nil {
		return nil, ErrorContext{
			Location: "template_file: " + templatePath,
			Reason:   "failed to resolve absolute path: " + err.Error(),
		}
	}

	// Check if file exists
	fileInfo, err := os.Stat(absPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, ErrorContext{
				Location: "template_file: " + absPath,
				Reason:   "file does not exist",
			}
		}
		return nil, ErrorContext{
			Location: "template_file: " + absPath,
			Reason:   "failed to stat file: " + err.Error(),
		}
	}

	// Check if it's a regular file
	if !fileInfo.Mode().IsRegular() {
		return nil, ErrorContext{
			Location: "template_file: " + absPath,
			Reason:   "path is not a regular file",
		}
	}

	// Check file size (limit to 10MB for safety)
	const maxTemplateSize = 10 * 1024 * 1024 // 10MB
	if fileInfo.Size() > maxTemplateSize {
		return nil, ErrorContext{
			Location: "template_file: " + absPath,
			Reason:   "template file is too large (max 10MB)",
		}
	}

	// Read the template file
	templateContent, err := os.ReadFile(absPath)
	if err != nil {
		return nil, ErrorContext{
			Location: "template_file: " + absPath,
			Reason:   "failed to read file: " + err.Error(),
		}
	}

	// Parse the template
	parsedTpl, err := tpl.Parse(string(templateContent))
	if err != nil {
		return nil, ErrorContext{
			Location: "template_file: " + absPath,
			Reason:   "failed to parse template: " + err.Error(),
		}
	}

	m.Debug("Template loaded successfully from: " + absPath)
	return parsedTpl, nil
}

const redactTpl = `{{ $data := . }}
// Code generated by protoc-gen-redact. DO NOT EDIT.
// source: {{ $data.Source }}

package {{ $data.Package }}

import (
	{{- range $alias, $path := $data.Imports }}
	{{ $alias }} "{{ $path }}"
	{{- end }}
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	{{- range $name := $data.References }}
	_ {{ $name }}
	{{- end }}
)

{{ range $srv := $data.Services }}
	{{- if $srv.Skip }}
		// Redacted server wrapper for {{ $srv.Name }} is skipped
		var RegisterRedacted{{ $srv.Name }} = Register{{ $srv.Name }}
	{{- else }}
		// RegisterRedacted{{ $srv.Name }} wraps the {{ $srv.Name }} with the redacted server and registers the service in GRPC
		func RegisterRedacted{{ $srv.Name }}(s grpc.ServiceRegistrar, srv {{ $srv.Name }}) {
			Register{{ $srv.Name }}(s, Redacted{{ $srv.Name }}(srv))
		}

		// RegisterRedacted{{ $srv.Name }}WithBypass 使用自定义内部调用绕过策略注册服务。
		func RegisterRedacted{{ $srv.Name }}WithBypass(s grpc.ServiceRegistrar, srv {{ $srv.Name }}, bypass redact.Bypass) {
			Register{{ $srv.Name }}(s, Redacted{{ $srv.Name }}WithBypass(srv, bypass))
		}

		func Redacted{{ $srv.Name }}(srv {{ $srv.Name }}) {{ $srv.Name }} {
			return Redacted{{ $srv.Name }}WithBypass(srv, nil)
		}

		// Redacted{{ $srv.Name }}WithBypass 创建带自定义内部调用绕过策略的服务包装器。
		func Redacted{{ $srv.Name }}WithBypass(srv {{ $srv.Name }}, bypass redact.Bypass) {{ $srv.Name }} {
			if bypass == nil {
				bypass = redact.Falsy
			}
			return &redacted{{ $srv.Name }}{srv: srv, bypass: bypass}
		}

		type redacted{{ $srv.Name }} struct {
			Unsafe{{ $srv.Name }}
			srv    {{ $srv.Name }}
			bypass redact.Bypass
		}

		{{ range $meth := $srv.Methods }}
			// {{ $meth.Name }} is the redacted wrapper for the actual {{ $srv.Name }}.{{ $meth.Name }} method
			{{- if and $meth.ClientStreaming $meth.ServerStreaming }}
				// Bidirectional streaming
				func (s *redacted{{ $srv.Name }}) {{ $meth.Name }}(stream grpc.BidiStreamingServer[{{ $meth.Input }}, {{ $meth.Output.WithAlias }}]) error {
					{{- if $meth.Skip }}
						// Redaction skipped
						return s.srv.{{ $meth.Name }}(stream)
					{{- else if $meth.Internal }}
						if s.bypass.CheckInternal(stream.Context()) {
							return s.srv.{{ $meth.Name }}(stream)
						}
						return status.Error(codes.{{ $meth.StatusCode }}, {{ $meth.ErrMessage }})
					{{- else }}
						if !s.bypass.CheckInternal(stream.Context()) {
							// Wrap stream to redact each response message
							stream = &redact.BidiStreamRedactor[{{ $meth.Input }}, {{ $meth.Output.WithAlias }}]{BidiStreamingServer: stream, Operation: "{{ $meth.FullMethod }}"}
						}
						return s.srv.{{ $meth.Name }}(stream)
					{{- end }}
				}
			{{- else if $meth.ClientStreaming }}
				// Client streaming
				func (s *redacted{{ $srv.Name }}) {{ $meth.Name }}(stream grpc.ClientStreamingServer[{{ $meth.Input }}, {{ $meth.Output.WithAlias }}]) error {
					{{- if $meth.Skip }}
						// Redaction skipped
						return s.srv.{{ $meth.Name }}(stream)
					{{- else if $meth.Internal }}
						if s.bypass.CheckInternal(stream.Context()) {
							return s.srv.{{ $meth.Name }}(stream)
						}
						return status.Error(codes.{{ $meth.StatusCode }}, {{ $meth.ErrMessage }})
					{{- else }}
						if !s.bypass.CheckInternal(stream.Context()) {
							// Wrap stream to redact the response message
							stream = &redact.ClientStreamRedactor[{{ $meth.Input }}, {{ $meth.Output.WithAlias }}]{ClientStreamingServer: stream, Operation: "{{ $meth.FullMethod }}"}
						}
						return s.srv.{{ $meth.Name }}(stream)
					{{- end }}
				}
			{{- else if $meth.ServerStreaming }}
				// Server streaming
				func (s *redacted{{ $srv.Name }}) {{ $meth.Name }}(in *{{ $meth.Input }}, stream grpc.ServerStreamingServer[{{ $meth.Output.WithAlias }}]) error {
					{{- if $meth.Skip }}
						// Redaction skipped
						return s.srv.{{ $meth.Name }}(in, stream)
					{{- else if $meth.Internal }}
						if s.bypass.CheckInternal(stream.Context()) {
							return s.srv.{{ $meth.Name }}(in, stream)
						}
						return status.Error(codes.{{ $meth.StatusCode }}, {{ $meth.ErrMessage }})
					{{- else }}
						if !s.bypass.CheckInternal(stream.Context()) {
							// Wrap stream to redact each response message
							stream = &redact.ServerStreamRedactor[{{ $meth.Output.WithAlias }}]{ServerStreamingServer: stream, Operation: "{{ $meth.FullMethod }}"}
						}
						return s.srv.{{ $meth.Name }}(in, stream)
					{{- end }}
				}
			{{- else }}
				// Unary RPC
				func (s *redacted{{ $srv.Name }}) {{ $meth.Name }}(ctx context.Context, in *{{ $meth.Input }}) (*{{ $meth.Output.WithAlias }}, error) {
					{{- if $meth.Skip }}
						// Redaction skipped
						return s.srv.{{ $meth.Name }}(ctx, in)
					{{- else if $meth.Internal }}
						if s.bypass.CheckInternal(ctx) {
							return s.srv.{{ $meth.Name }}(ctx, in)
						}
						return nil, status.Error(codes.{{ $meth.StatusCode }}, {{ $meth.ErrMessage }})
					{{- else }}
						res, err := s.srv.{{ $meth.Name }}(ctx, in)
						if !s.bypass.CheckInternal(ctx) {
							{{- if $meth.Output.ToNil }}
								// Response message is set to nil, ignoring all field level rules
								res = nil
							{{- else if $meth.Output.ToEmpty }}
								// Response message is set to empty, ignoring all field level rules
								res = &{{ $meth.Output.WithAlias }}{}
							{{- else if $meth.Output.Ignore  }}
								// Response message is set to be ignored from any redaction
							{{- else }}
								// Apply redaction to the response
								redact.ApplyWith(redact.WithDirection(redact.WithOperation(ctx, "{{ $meth.FullMethod }}"), redact.DirectionResponse), nil, res)
							{{- end }}
						}
						return res, err
					{{- end }}
				}
			{{- end }}
		{{ end }}
	{{ end }}
{{ end }}

{{ range $msg := $data.Messages }}
	// Ensure {{ $msg.Name }} implements the Redactor interface at compile time.
	var _ redact.Redactor = (*{{ $msg.Name }})(nil)

	// Redact method implementation for {{ $msg.Name }}
	func (x *{{ $msg.Name }}) Redact() {
		{{- if $msg.Ignore }}
			// Ignoring message
		{{- else if $msg.ToEmpty }}
			// Message will be set to empty, ignoring all field level rules
		{{- else if $msg.ToNil }}
			// Message will be set to nil, ignoring all field level rules
		{{- else }}
			if x == nil { return }
			{{- range $field := $msg.Fields }}
				{{ if $field.Redact }}
					// Redacting field: {{ $field.Name }}
					{{- if $field.IsCondition }}
						if redact.Condition({{ $field.CondEnvVar }}, {{ $field.CondEnvVal }}) {
					{{- end }}
					{{- if $field.IsRegex }}
						{{- if $field.IsOptional }}
							if x.{{ $field.Name }} != nil {
								{{ $field.Name }}RegexTmp := redact.Regex(*x.{{ $field.Name }}, {{ $field.RegexPatternLiteral }}, {{ $field.RegexReplacement }})
								x.{{ $field.Name }} = &{{ $field.Name }}RegexTmp
							}
						{{- else if $field.Iterate }}
							for _regexIdx := range x.{{ $field.Name }} {
								x.{{ $field.Name }}[_regexIdx] = redact.Regex(x.{{ $field.Name }}[_regexIdx], {{ $field.RegexPatternLiteral }}, {{ $field.RegexReplacement }})
							}
						{{- else }}
							x.{{ $field.Name }} = redact.Regex(x.{{ $field.Name }}, {{ $field.RegexPatternLiteral }}, {{ $field.RegexReplacement }})
						{{- end }}
					{{- else if $field.IsMask }}
						{{- if $field.IsOptional }}
							if x.{{ $field.Name }} != nil {
								{{ $field.Name }}MaskTmp := redact.Mask(*x.{{ $field.Name }}, {{ $field.MaskKeepFirst }}, {{ $field.MaskKeepLast }}, {{ $field.MaskChar }})
								x.{{ $field.Name }} = &{{ $field.Name }}MaskTmp
							}
						{{- else if $field.Iterate }}
							for _maskIdx := range x.{{ $field.Name }} {
								x.{{ $field.Name }}[_maskIdx] = redact.Mask(x.{{ $field.Name }}[_maskIdx], {{ $field.MaskKeepFirst }}, {{ $field.MaskKeepLast }}, {{ $field.MaskChar }})
							}
						{{- else }}
							x.{{ $field.Name }} = redact.Mask(x.{{ $field.Name }}, {{ $field.MaskKeepFirst }}, {{ $field.MaskKeepLast }}, {{ $field.MaskChar }})
						{{- end }}
					{{- else if $field.IsEmail }}
						{{- if $field.IsOptional }}
							if x.{{ $field.Name }} != nil {
								{{ $field.Name }}EmailTmp := redact.Email(*x.{{ $field.Name }}, {{ $field.EmailKeepLocalFirst }}, {{ $field.EmailMaskDomain }}, {{ $field.EmailMaskChar }})
								x.{{ $field.Name }} = &{{ $field.Name }}EmailTmp
							}
						{{- else if $field.Iterate }}
							for _emailIdx := range x.{{ $field.Name }} {
								x.{{ $field.Name }}[_emailIdx] = redact.Email(x.{{ $field.Name }}[_emailIdx], {{ $field.EmailKeepLocalFirst }}, {{ $field.EmailMaskDomain }}, {{ $field.EmailMaskChar }})
							}
						{{- else }}
							x.{{ $field.Name }} = redact.Email(x.{{ $field.Name }}, {{ $field.EmailKeepLocalFirst }}, {{ $field.EmailMaskDomain }}, {{ $field.EmailMaskChar }})
						{{- end }}
					{{- else if $field.IsTruncate }}
						{{- if $field.IsOptional }}
							if x.{{ $field.Name }} != nil {
								{{ $field.Name }}TruncTmp := redact.Truncate(*x.{{ $field.Name }}, {{ $field.TruncateLength }}, {{ $field.TruncateSuffix }})
								x.{{ $field.Name }} = &{{ $field.Name }}TruncTmp
							}
						{{- else if $field.Iterate }}
							for _truncIdx := range x.{{ $field.Name }} {
								x.{{ $field.Name }}[_truncIdx] = redact.Truncate(x.{{ $field.Name }}[_truncIdx], {{ $field.TruncateLength }}, {{ $field.TruncateSuffix }})
							}
						{{- else }}
							x.{{ $field.Name }} = redact.Truncate(x.{{ $field.Name }}, {{ $field.TruncateLength }}, {{ $field.TruncateSuffix }})
						{{- end }}
					{{- else if $field.IsHash }}
						{{- if $field.IsOptional }}
							if x.{{ $field.Name }} != nil {
								{{ $field.Name }}HashTmp := {{ $field.HashFuncName }}(*x.{{ $field.Name }})
								x.{{ $field.Name }} = &{{ $field.Name }}HashTmp
							}
						{{- else if $field.Iterate }}
							for _hashIdx := range x.{{ $field.Name }} {
								x.{{ $field.Name }}[_hashIdx] = {{ $field.HashFuncName }}(x.{{ $field.Name }}[_hashIdx])
							}
						{{- else }}
							x.{{ $field.Name }} = {{ $field.HashFuncName }}(x.{{ $field.Name }})
						{{- end }}
					{{- else if $field.IsUUID }}
						{{- if $field.IsOptional }}
							if x.{{ $field.Name }} != nil {
								{{ $field.Name }}UUIDTmp := redact.UUID(*x.{{ $field.Name }})
								x.{{ $field.Name }} = &{{ $field.Name }}UUIDTmp
							}
						{{- else if $field.Iterate }}
							for _uuidIdx := range x.{{ $field.Name }} {
								x.{{ $field.Name }}[_uuidIdx] = redact.UUID(x.{{ $field.Name }}[_uuidIdx])
							}
						{{- else }}
							x.{{ $field.Name }} = redact.UUID(x.{{ $field.Name }})
						{{- end }}
					{{- else if $field.IsIP }}
						{{- if $field.IsOptional }}
							if x.{{ $field.Name }} != nil {
								{{ $field.Name }}IPTmp := redact.IP(*x.{{ $field.Name }}, {{ $field.IPKeepOctets }}, {{ $field.IPMaskChar }})
								x.{{ $field.Name }} = &{{ $field.Name }}IPTmp
							}
						{{- else if $field.Iterate }}
							for _ipIdx := range x.{{ $field.Name }} {
								x.{{ $field.Name }}[_ipIdx] = redact.IP(x.{{ $field.Name }}[_ipIdx], {{ $field.IPKeepOctets }}, {{ $field.IPMaskChar }})
							}
						{{- else }}
							x.{{ $field.Name }} = redact.IP(x.{{ $field.Name }}, {{ $field.IPKeepOctets }}, {{ $field.IPMaskChar }})
						{{- end }}
					{{- else if $field.IsURL }}
						{{- if $field.IsOptional }}
							if x.{{ $field.Name }} != nil {
								{{ $field.Name }}URLTmp := redact.URL(*x.{{ $field.Name }}, {{ $field.URLMaskQuery }}, {{ $field.URLMaskChar }})
								x.{{ $field.Name }} = &{{ $field.Name }}URLTmp
							}
						{{- else if $field.Iterate }}
							for _urlIdx := range x.{{ $field.Name }} {
								x.{{ $field.Name }}[_urlIdx] = redact.URL(x.{{ $field.Name }}[_urlIdx], {{ $field.URLMaskQuery }}, {{ $field.URLMaskChar }})
							}
						{{- else }}
							x.{{ $field.Name }} = redact.URL(x.{{ $field.Name }}, {{ $field.URLMaskQuery }}, {{ $field.URLMaskChar }})
						{{- end }}
					{{- else if $field.IsFixedLength }}
						{{- if $field.IsOptional }}
							if x.{{ $field.Name }} != nil {
								{{ $field.Name }}FixTmp := redact.FixedLength(*x.{{ $field.Name }}, {{ $field.FixedLengthChar }})
								x.{{ $field.Name }} = &{{ $field.Name }}FixTmp
							}
						{{- else if $field.Iterate }}
							for _fixIdx := range x.{{ $field.Name }} {
								x.{{ $field.Name }}[_fixIdx] = redact.FixedLength(x.{{ $field.Name }}[_fixIdx], {{ $field.FixedLengthChar }})
							}
						{{- else }}
							x.{{ $field.Name }} = redact.FixedLength(x.{{ $field.Name }}, {{ $field.FixedLengthChar }})
						{{- end }}
					{{- else if $field.IsCustom }}
						{{- if $field.IsOptional }}
							if x.{{ $field.Name }} != nil {
								{{ $field.Name }}CustomTmp := redact.ApplyCustomRedactor({{ $field.CustomFuncName }}, *x.{{ $field.Name }})
								x.{{ $field.Name }} = &{{ $field.Name }}CustomTmp
							}
						{{- else if $field.Iterate }}
							for _customIdx := range x.{{ $field.Name }} {
								x.{{ $field.Name }}[_customIdx] = redact.ApplyCustomRedactor({{ $field.CustomFuncName }}, x.{{ $field.Name }}[_customIdx])
							}
						{{- else }}
							x.{{ $field.Name }} = redact.ApplyCustomRedactor({{ $field.CustomFuncName }}, x.{{ $field.Name }})
						{{- end }}
					{{- else if $field.Iterate }}
						{{- if $field.NestedEmbedCall }}
							for k := range x.{{ $field.Name }} {
								redact.Apply(x.{{$field.Name}}[k])
							}
						{{- else if $field.EmbedSkip }}
							// {{$field.Name}} redaction is skipped
                        {{- else }}
							for k := range x.{{ $field.Name }} {
								x.{{ $field.Name }}[k] = {{ $field.RedactionValue }}
							}
						{{- end }}
                    {{- else if $field.IsMessage }}
						{{- if $field.NestedEmbedCall }}
							redact.Apply(x.{{$field.Name}})
						{{- else if $field.EmbedSkip }}
							// {{$field.Name}} redaction is skipped
                        {{- else }}
							x.{{ $field.Name }} = {{ $field.RedactionValue }}
						{{- end }}
                    {{- else }}
						{{- if $field.IsOptional }}
							{{- if eq $field.FieldGoType "string" }}
								{{ $field.Name }}Tmp := {{ $field.RedactionValue }}
								x.{{ $field.Name }} = &{{ $field.Name }}Tmp
							{{- else }}
								{{ $field.Name }}Tmp := {{ $field.FieldGoType }}({{ $field.RedactionValue }})
								x.{{ $field.Name }} = &{{ $field.Name }}Tmp
							{{- end }}
						{{- else }}
							x.{{ $field.Name }} = {{ $field.RedactionValue }}
						{{- end }}
					{{- end }}
					{{- if $field.IsCondition }}
						}
					{{- end }}
				{{- else }}
					// Safe field: {{ $field.Name }}
				{{- end }}
			{{- end }}
			{{- range $oneof := $msg.Oneofs }}
				{{- if $oneof.HasRedactableFields }}
				// Redacting oneof: {{ $oneof.Name }}
				switch v := x.{{ $oneof.Name }}.(type) {
				{{- range $field := $oneof.Fields }}
					{{- if $field.Redact }}
					case *{{ $field.WrapperTypeName }}:
						{{- if $field.IsCondition }}
							if redact.Condition({{ $field.CondEnvVar }}, {{ $field.CondEnvVal }}) {
						{{- end }}
						{{- if $field.IsRegex }}
							v.{{ $field.Name }} = redact.Regex(v.{{ $field.Name }}, {{ $field.RegexPatternLiteral }}, {{ $field.RegexReplacement }})
						{{- else if $field.IsMask }}
							v.{{ $field.Name }} = redact.Mask(v.{{ $field.Name }}, {{ $field.MaskKeepFirst }}, {{ $field.MaskKeepLast }}, {{ $field.MaskChar }})
						{{- else if $field.IsEmail }}
							v.{{ $field.Name }} = redact.Email(v.{{ $field.Name }}, {{ $field.EmailKeepLocalFirst }}, {{ $field.EmailMaskDomain }}, {{ $field.EmailMaskChar }})
						{{- else if $field.IsTruncate }}
							v.{{ $field.Name }} = redact.Truncate(v.{{ $field.Name }}, {{ $field.TruncateLength }}, {{ $field.TruncateSuffix }})
						{{- else if $field.IsHash }}
							v.{{ $field.Name }} = {{ $field.HashFuncName }}(v.{{ $field.Name }})
						{{- else if $field.IsUUID }}
							v.{{ $field.Name }} = redact.UUID(v.{{ $field.Name }})
						{{- else if $field.IsIP }}
							v.{{ $field.Name }} = redact.IP(v.{{ $field.Name }}, {{ $field.IPKeepOctets }}, {{ $field.IPMaskChar }})
						{{- else if $field.IsURL }}
							v.{{ $field.Name }} = redact.URL(v.{{ $field.Name }}, {{ $field.URLMaskQuery }}, {{ $field.URLMaskChar }})
						{{- else if $field.IsFixedLength }}
							v.{{ $field.Name }} = redact.FixedLength(v.{{ $field.Name }}, {{ $field.FixedLengthChar }})
						{{- else if $field.IsCustom }}
							v.{{ $field.Name }} = redact.ApplyCustomRedactor({{ $field.CustomFuncName }}, v.{{ $field.Name }})
						{{- else if $field.IsMessage }}
							{{- if $field.NestedEmbedCall }}
								redact.Apply(v.{{ $field.Name }})
							{{- else if $field.EmbedSkip }}
								// {{ $field.Name }} redaction is skipped
							{{- else }}
								v.{{ $field.Name }} = {{ $field.RedactionValue }}
							{{- end }}
						{{- else }}
							v.{{ $field.Name }} = {{ $field.RedactionValue }}
						{{- end }}
						{{- if $field.IsCondition }}
							}
						{{- end }}
					{{- end }}
				{{- end }}
				}
				{{- end }}
			{{- end }}
		{{- end }}
	}
{{ end }}
`
