package main

import (
	"bytes"
	"embed"
	"fmt"
	"strconv"
	"text/template"

	"github.com/liujitcn/kratos-kit/cmd/internal/utils"
	kitutils "github.com/liujitcn/kratos-kit/utils"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/descriptorpb"
)

const (
	jsonPackage      = protogen.GoImportPath("encoding/json")
	contextPackage   = protogen.GoImportPath("context")
	einoToolPackage  = protogen.GoImportPath("github.com/cloudwego/eino/components/tool")
	einoToolUtilsPkg = protogen.GoImportPath("github.com/cloudwego/eino/components/tool/utils")
)

const deprecationComment = "// Deprecated: Do not use."

//go:embed templates/agent_tool.go.tmpl
var agentToolTemplates embed.FS

var agentToolTemplate = template.Must(template.ParseFS(agentToolTemplates, "templates/agent_tool.go.tmpl"))

type agentToolTemplateData struct {
	ContextPackage string
	JSONMarshal    string
	JSONUnmarshal  string
	InvokableTool  string
	InferTool      string
	Services       []agentServiceTemplateData
}

type agentServiceTemplateData struct {
	DeprecatedComment string
	Comment           string
	Name              string
	ServerName        string
	HasMethods        bool
	Methods           []agentMethodTemplateData
}

type agentMethodTemplateData struct {
	DeprecatedComment string
	Comment           string
	Name              string
	ServiceName       string
	ServerName        string
	ConstructorName   string
	ToolVar           string
	RequestType       string
	InputType         string
	OutputType        string
	RequestValue      string
	ToolName          string
	Description       string
}

// generateAgentToolFile 生成 Agent Tool 文件。
func generateAgentToolFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if len(file.Services) == 0 {
		return nil
	}

	filename := file.GeneratedFilenamePrefix + "_agent_tool.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-agent-tool.")
	g.P("// versions:")
	g.P(fmt.Sprintf("// - protoc-gen-go-agent-tool %s", release))
	g.P("// - protoc                    ", utils.ProtocVersion(gen))
	if file.Proto.GetOptions().GetDeprecated() {
		g.P("// ", file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", file.Desc.Path())
	}
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	templateContent, err := renderAgentToolTemplate(g, file)
	if err != nil {
		panic(err)
	}
	g.P(templateContent)

	var content []byte
	content, err = g.Content()
	if err != nil {
		panic(err)
	}
	content, err = utils.FormatGeneratedContent(filename, content)
	if err != nil {
		panic(err)
	}

	g.Skip()
	cleanFile := gen.NewGeneratedFile(filename, "")
	_, _ = cleanFile.Write(content)
	return cleanFile
}

// renderAgentToolTemplate 使用模板生成 Agent Tool 文件主体，并提前登记所需导入。
func renderAgentToolTemplate(g *protogen.GeneratedFile, file *protogen.File) (string, error) {
	data := agentToolTemplateData{
		ContextPackage: g.QualifiedGoIdent(contextPackage.Ident("Context")),
		JSONMarshal:    g.QualifiedGoIdent(jsonPackage.Ident("Marshal")),
		JSONUnmarshal:  g.QualifiedGoIdent(jsonPackage.Ident("Unmarshal")),
		InvokableTool:  g.QualifiedGoIdent(einoToolPackage.Ident("InvokableTool")),
		InferTool:      g.QualifiedGoIdent(einoToolUtilsPkg.Ident("InferTool")),
		Services:       make([]agentServiceTemplateData, 0, len(file.Services)),
	}
	for _, service := range file.Services {
		data.Services = append(data.Services, newAgentServiceTemplateData(g, service))
	}
	var output bytes.Buffer
	err := agentToolTemplate.Execute(&output, data)
	if err != nil {
		return "", err
	}
	return output.String(), nil
}

// newAgentServiceTemplateData 构造一个 Agent service 的模板数据。
func newAgentServiceTemplateData(g *protogen.GeneratedFile, service *protogen.Service) agentServiceTemplateData {
	serviceName := service.GoName
	data := agentServiceTemplateData{
		Comment:    formatTypeComment("New"+serviceName+"AgentTools", utils.NormalizeCommentText(service.Comments.Leading)),
		Name:       serviceName,
		ServerName: utils.Unexport(serviceName) + "Server",
		Methods:    make([]agentMethodTemplateData, 0, len(service.Methods)),
	}
	if service.Desc.Options().(*descriptorpb.ServiceOptions).GetDeprecated() {
		data.DeprecatedComment = deprecationComment
	}
	for _, method := range service.Methods {
		if !utils.IsUnaryMethod(method) {
			continue
		}
		data.Methods = append(data.Methods, newAgentMethodTemplateData(g, service, method))
	}
	data.HasMethods = len(data.Methods) > 0
	return data
}

// newAgentMethodTemplateData 构造一个一元 RPC 的 Agent Tool 模板数据。
func newAgentMethodTemplateData(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method) agentMethodTemplateData {
	requestType := g.QualifiedGoIdent(method.Input.GoIdent)
	responseType := g.QualifiedGoIdent(method.Output.GoIdent)
	inputType := "*" + requestType
	outputType := "*" + responseType
	requestValue := "req"
	if messageHasRecursiveReference(method.Input) {
		inputType = "any"
		requestValue = "realReq"
	}
	if messageHasRecursiveReference(method.Output) {
		outputType = "any"
	}
	data := agentMethodTemplateData{
		Comment:         formatMethodComment("New"+service.GoName+method.GoName+"AgentTool", utils.NormalizeCommentText(method.Comments.Leading)),
		Name:            method.GoName,
		ServiceName:     service.GoName,
		ServerName:      utils.Unexport(service.GoName) + "Server",
		ConstructorName: "New" + service.GoName + method.GoName + "AgentTool",
		ToolVar:         utils.Unexport(method.GoName) + "Tool",
		RequestType:     requestType,
		InputType:       inputType,
		OutputType:      outputType,
		RequestValue:    requestValue,
		ToolName:        strconv.Quote(kitutils.ToolNameFromRPCPath("/" + string(service.Desc.FullName()) + "/" + string(method.Desc.Name()))),
		Description:     strconv.Quote(utils.ToolDescription(service, method)),
	}
	if method.Desc.Options().(*descriptorpb.MethodOptions).GetDeprecated() {
		data.DeprecatedComment = deprecationComment
	}
	return data
}

// messageHasRecursiveReference 判断 message 依赖图中是否存在递归引用。
func messageHasRecursiveReference(message *protogen.Message) bool {
	if message == nil {
		return false
	}
	visiting := make(map[protogen.GoIdent]bool)
	visited := make(map[protogen.GoIdent]bool)
	return messageHasRecursiveReferenceInStack(message, visiting, visited)
}

// messageHasRecursiveReferenceInStack 深度遍历 message 字段，发现回到当前访问栈时视为递归。
func messageHasRecursiveReferenceInStack(message *protogen.Message, visiting, visited map[protogen.GoIdent]bool) bool {
	if message == nil {
		return false
	}
	ident := message.GoIdent
	if visiting[ident] {
		return true
	}
	if visited[ident] {
		return false
	}
	visiting[ident] = true
	defer delete(visiting, ident)

	for _, field := range message.Fields {
		if field.Message == nil {
			continue
		}
		if messageHasRecursiveReferenceInStack(field.Message, visiting, visited) {
			return true
		}
	}

	visited[ident] = true
	return false
}

// formatTypeComment 生成类型或构造函数注释，统一采用“名称 描述”格式。
func formatTypeComment(name, comment string) string {
	if comment == "" {
		return "// " + name
	}
	return utils.FormatToolActionComment(name, comment, "创建", "Agent Tool")
}

// formatMethodComment 生成方法注释，保持“// 方法名 描述”的输出样式。
func formatMethodComment(name, comment string) string {
	if comment == "" {
		return "// " + name
	}
	return utils.FormatToolActionComment(name, comment, "创建", "Agent Tool")
}
