package main

import (
	"fmt"
	"strconv"

	"github.com/liujitcn/kratos-kit/cmd/internal/utils"
	kitutils "github.com/liujitcn/kratos-kit/utils"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/descriptorpb"
)

const (
	jsonPackage      = protogen.GoImportPath("encoding/json")
	contextPackage   = protogen.GoImportPath("context")
	einoToolPackage  = protogen.GoImportPath("github.com/cloudwego/eino/components/tool")
	einoToolUtilsPkg = protogen.GoImportPath("github.com/cloudwego/eino/components/tool/utils")
)

const deprecationComment = "// Deprecated: Do not use."

// generateAgentToolFile 生成 Agent Tool 文件。
func generateAgentToolFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if len(file.Services) == 0 {
		return nil
	}

	filename := file.GeneratedFilenamePrefix + "_agent_tool.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-agent-tool.")
	g.P("// versions:")
	g.P(fmt.Sprintf("// - protoc-gen-go-agent-tool %s", release))
	g.P("// - protoc                    ", utils.ProtocVersion(gen))
	if file.Proto.GetOptions().GetDeprecated() {
		g.P("// ", file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", file.Desc.Path())
	}
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	generateAgentToolFileContent(g, file)

	content, err := g.Content()
	if err != nil {
		panic(err)
	}
	content, err = utils.FormatGeneratedContent(filename, content)
	if err != nil {
		panic(err)
	}

	g.Skip()
	cleanFile := gen.NewGeneratedFile(filename, "")
	_, _ = cleanFile.Write(content)
	return cleanFile
}

// generateAgentToolFileContent 生成 Agent Tool 文件主体内容。
func generateAgentToolFileContent(g *protogen.GeneratedFile, file *protogen.File) {
	for _, service := range file.Services {
		generateServiceAgentTools(g, service)
	}
}

// generateServiceAgentTools 为一个 proto service 生成 Tool 集合构造函数与各 RPC Tool 构造函数。
func generateServiceAgentTools(g *protogen.GeneratedFile, service *protogen.Service) {
	if service.Desc.Options().(*descriptorpb.ServiceOptions).GetDeprecated() {
		g.P(deprecationComment)
	}

	serviceName := service.GoName
	serverName := utils.Unexport(serviceName) + "Server"
	g.P(formatTypeComment("New"+serviceName+"AgentTools", utils.NormalizeCommentText(service.Comments.Leading)))
	g.P("func New", serviceName, "AgentTools(", serverName, " ", service.GoName, "Server) ([]", g.QualifiedGoIdent(einoToolPackage.Ident("InvokableTool")), ", error) {")
	g.P("var ts []", g.QualifiedGoIdent(einoToolPackage.Ident("InvokableTool")))
	g.P("var err error")
	for _, method := range service.Methods {
		if !utils.IsUnaryMethod(method) {
			continue
		}
		toolVar := utils.Unexport(method.GoName) + "Tool"
		g.P("var ", toolVar, " ", g.QualifiedGoIdent(einoToolPackage.Ident("InvokableTool")))
		g.P(toolVar, ", err = New", serviceName, method.GoName, "AgentTool(", serverName, ")")
		g.P("if err != nil {")
		g.P("return nil, err")
		g.P("}")
		g.P("ts = append(ts, ", toolVar, ")")
	}
	g.P("return ts, nil")
	g.P("}")
	g.P()

	for _, method := range service.Methods {
		if !utils.IsUnaryMethod(method) {
			continue
		}
		generateMethodAgentTool(g, service, method)
	}
}

// generateMethodAgentTool 为一个一元 RPC 生成 Agent Tool 构造函数。
func generateMethodAgentTool(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method) {
	toolName := kitutils.ToolNameFromRPCPath("/" + string(service.Desc.FullName()) + "/" + string(method.Desc.Name()))
	description := utils.ToolDescription(service, method)
	serverName := utils.Unexport(service.GoName) + "Server"
	requestType := g.QualifiedGoIdent(method.Input.GoIdent)
	responseType := g.QualifiedGoIdent(method.Output.GoIdent)
	inputType := "*" + requestType
	outputType := "*" + responseType
	if messageHasRecursiveReference(method.Input) {
		inputType = "any"
	}
	if messageHasRecursiveReference(method.Output) {
		outputType = "any"
	}

	if method.Desc.Options().(*descriptorpb.MethodOptions).GetDeprecated() {
		g.P(deprecationComment)
	}
	g.P(formatMethodComment("New"+service.GoName+method.GoName+"AgentTool", utils.NormalizeCommentText(method.Comments.Leading)))
	g.P("func New", service.GoName, method.GoName, "AgentTool(", serverName, " ", service.GoName, "Server) (", g.QualifiedGoIdent(einoToolPackage.Ident("InvokableTool")), ", error) {")
	g.P("return ", g.QualifiedGoIdent(einoToolUtilsPkg.Ident("InferTool")), "[", inputType, ", ", outputType, "](")
	g.P(strconv.Quote(toolName), ",")
	g.P(strconv.Quote(description), ",")
	g.P("func(ctx ", g.QualifiedGoIdent(contextPackage.Ident("Context")), ", req ", inputType, ") (", outputType, ", error) {")
	if inputType == "any" {
		g.P("realReq := &", requestType, "{}")
		g.P("if req != nil {")
		g.P("reqBytes, err := ", g.QualifiedGoIdent(jsonPackage.Ident("Marshal")), "(req)")
		g.P("if err != nil {")
		g.P("return nil, err")
		g.P("}")
		g.P("if err = ", g.QualifiedGoIdent(jsonPackage.Ident("Unmarshal")), "(reqBytes, realReq); err != nil {")
		g.P("return nil, err")
		g.P("}")
		g.P("}")
	} else {
		g.P("if req == nil {")
		g.P("req = &", requestType, "{}")
		g.P("}")
	}
	requestValue := "req"
	if inputType == "any" {
		requestValue = "realReq"
	}
	if outputType == "any" {
		g.P("reply, err := ", serverName, ".", method.GoName, "(ctx, ", requestValue, ")")
		g.P("if err != nil {")
		g.P("return nil, err")
		g.P("}")
		g.P("return reply, nil")
	} else {
		g.P("return ", serverName, ".", method.GoName, "(ctx, ", requestValue, ")")
	}
	g.P("},")
	g.P(")")
	g.P("}")
	g.P()
}

// messageHasRecursiveReference 判断 message 依赖图中是否存在递归引用。
func messageHasRecursiveReference(message *protogen.Message) bool {
	if message == nil {
		return false
	}
	visiting := make(map[protogen.GoIdent]bool)
	visited := make(map[protogen.GoIdent]bool)
	return messageHasRecursiveReferenceInStack(message, visiting, visited)
}

// messageHasRecursiveReferenceInStack 深度遍历 message 字段，发现回到当前访问栈时视为递归。
func messageHasRecursiveReferenceInStack(message *protogen.Message, visiting, visited map[protogen.GoIdent]bool) bool {
	if message == nil {
		return false
	}
	ident := message.GoIdent
	if visiting[ident] {
		return true
	}
	if visited[ident] {
		return false
	}
	visiting[ident] = true
	defer delete(visiting, ident)

	for _, field := range message.Fields {
		if field.Message == nil {
			continue
		}
		if messageHasRecursiveReferenceInStack(field.Message, visiting, visited) {
			return true
		}
	}

	visited[ident] = true
	return false
}

// formatTypeComment 生成类型或构造函数注释，统一采用“名称 描述”格式。
func formatTypeComment(name, comment string) string {
	if comment == "" {
		return "// " + name
	}
	return utils.FormatToolActionComment(name, comment, "创建", "Agent Tool")
}

// formatMethodComment 生成方法注释，保持“// 方法名 描述”的输出样式。
func formatMethodComment(name, comment string) string {
	if comment == "" {
		return "// " + name
	}
	return utils.FormatToolActionComment(name, comment, "创建", "Agent Tool")
}
