package main

import (
	"fmt"
	"path"
	"strconv"
	"strings"

	cmdutils "github.com/liujitcn/kratos-kit/cmd/internal/utils"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/descriptorpb"
)

const (
	contextPackage  = protogen.GoImportPath("context")
	dataPackage     = protogen.GoImportPath("github.com/liujitcn/shop-gorm-gen/data")
	grpcPackage     = protogen.GoImportPath("google.golang.org/grpc")
	codesPackage    = protogen.GoImportPath("google.golang.org/grpc/codes")
	statusPackage   = protogen.GoImportPath("google.golang.org/grpc/status")
	logPackage      = protogen.GoImportPath("github.com/go-kratos/kratos/v3/log")
	baseCasePackage = protogen.GoImportPath("github.com/liujitcn/shop-base/server/biz")
)

const deprecationComment = "// Deprecated: Do not use."

// generateServiceFile 生成 gRPC service 实现桩代码文件。
func generateServiceFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if len(file.Services) == 0 {
		return nil
	}
	filename := file.GeneratedFilenamePrefix + "_service.go"
	g := gen.NewGeneratedFile(filename, protogen.GoImportPath(file.GoPackageName))
	g.P("// Code generated by protoc-gen-go-service.")
	g.P("// versions:")
	g.P(fmt.Sprintf("// - protoc-gen-go-service %s", release))
	g.P("// - protoc             ", cmdutils.ProtocVersion(gen))
	if file.Proto.GetOptions().GetDeprecated() {
		g.P("// ", file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", file.Desc.Path())
	}
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	generateServiceFileContent(gen, file, g)

	content, err := g.Content()
	if err != nil {
		panic(err)
	}
	content, err = cmdutils.StripRedundantImportAliases(content)
	if err != nil {
		panic(err)
	}
	content, err = cmdutils.FormatGeneratedContent(filename, content)
	if err != nil {
		panic(err)
	}

	// 跳过原始生成文件，改为输出清理过 import 别名的最终内容。
	g.Skip()
	cleanFile := gen.NewGeneratedFile(filename, "")
	_, _ = cleanFile.Write(content)
	return cleanFile
}

// generateBizFile 生成 biz 层 Case 模版代码文件。
func generateBizFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if len(file.Services) == 0 {
		return nil
	}

	filename := bizFilename(file)
	g := gen.NewGeneratedFile(filename, bizImportPath(file))
	g.P("// Code generated by protoc-gen-go-service.")
	g.P("// versions:")
	g.P(fmt.Sprintf("// - protoc-gen-go-service %s", release))
	g.P("// - protoc             ", cmdutils.ProtocVersion(gen))
	if file.Proto.GetOptions().GetDeprecated() {
		g.P("// ", file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", file.Desc.Path())
	}
	g.P()
	g.P("package biz")
	g.P()
	generateBizFileContent(file, g)

	content, err := g.Content()
	if err != nil {
		panic(err)
	}
	content, err = cmdutils.StripRedundantImportAliases(content)
	if err != nil {
		panic(err)
	}
	content, err = cmdutils.FormatGeneratedContent(filename, content)
	if err != nil {
		panic(err)
	}

	g.Skip()
	cleanFile := gen.NewGeneratedFile(filename, "")
	_, _ = cleanFile.Write(content)
	return cleanFile
}

// generateServiceFileContent 生成除 package 外的 service 实现内容。
func generateServiceFileContent(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile) {
	if len(file.Services) == 0 {
		return
	}

	g.P("const _ = ", grpcPackage.Ident("SupportPackageIsVersion7")) // When changing, update version number above.
	g.P()

	for _, service := range file.Services {
		generateServiceStruct(gen, file, g, service)
	}
}

// generateBizFileContent 生成 biz 文件内容。
func generateBizFileContent(file *protogen.File, g *protogen.GeneratedFile) {
	for _, service := range file.Services {
		generateBizStruct(file, g, service)
	}
}

// generateServiceStruct 为单个 proto service 生成实现结构与方法桩代码。
func generateServiceStruct(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile, service *protogen.Service) {
	bizPackage := bizImportPath(file)
	serverType := service.GoName
	caseName := serviceCaseName(service)
	caseFieldName := cmdutils.Unexport(strings.TrimSuffix(caseName, "Case")) + "Case"
	serviceComment := cmdutils.NormalizeCommentText(service.Comments.Leading)

	// 结构体中内嵌未实现服务与 biz 层 Case，统一由 Case 承载基础上下文依赖。
	g.P(formatTypeComment(serverType, serviceComment))
	g.P("type ", serverType, " struct {")
	g.P(goIdent(g, file.GoDescriptorIdent.GoImportPath.Ident("Unimplemented"+service.GoName+"Server")))
	g.P(caseFieldName, " *", g.QualifiedGoIdent(bizPackage.Ident(caseName)))
	g.P("}")
	g.P()

	if service.Desc.Options().(*descriptorpb.ServiceOptions).GetDeprecated() {
		g.P(deprecationComment)
	}
	g.P(formatTypeComment("New"+serverType, serviceComment))
	g.P("func New", serverType, " (", caseFieldName, " *", g.QualifiedGoIdent(bizPackage.Ident(caseName)), ") *", serverType, " {")
	g.P("var ss =", serverType, " {")
	g.P(caseFieldName, ": ", caseFieldName, ",")
	g.P("}")
	g.P("return &", "ss")
	g.P("}")
	g.P()

	for _, method := range service.Methods {
		g.P(formatMethodComment(method.GoName, cmdutils.NormalizeCommentText(method.Comments.Leading)))
		g.P("func (s *", serverType, ") ", serverSignature(g, method), "{")
		if cmdutils.IsUnaryMethod(method) {
			generateUnaryMethodBody(g, file, method, caseFieldName)
		} else {
			g.P("var err error")
			g.P("// 流式方法暂未提供固定业务模版，保留未实现占位。")
			g.P("err = ", statusPackage.Ident("Errorf"), "(", codesPackage.Ident("Unimplemented"), `, "method `, method.GoName, ` not implemented")`)
			g.P("return err")
		}
		g.P("}")
	}
	g.P()
}

// generateBizStruct 生成 biz 层 Case 结构与方法模版。
func generateBizStruct(file *protogen.File, g *protogen.GeneratedFile, service *protogen.Service) {
	caseName := serviceCaseName(service)
	repoName := serviceRepoName(service)
	repoFieldName := repoName
	repoArgName := cmdutils.Unexport(repoName)
	baseCaseType := g.QualifiedGoIdent(baseCasePackage.Ident("BaseCase"))
	serviceComment := cmdutils.NormalizeCommentText(service.Comments.Leading)

	g.P(formatTypeComment(caseName, serviceComment))
	g.P("type ", caseName, " struct {")
	g.P("*", baseCaseType)
	g.P("*", g.QualifiedGoIdent(dataPackage.Ident(repoFieldName)))
	g.P("}")
	g.P()

	g.P(formatTypeComment("New"+caseName, serviceComment))
	g.P("func New", caseName, "(")
	g.P("baseCase *", baseCaseType, ",")
	g.P(repoArgName, " *", g.QualifiedGoIdent(dataPackage.Ident(repoName)), ",")
	g.P(") *", caseName, " {")
	g.P("return &", caseName, "{")
	g.P("BaseCase: ", "baseCase,")
	g.P(repoFieldName, ": ", repoArgName, ",")
	g.P("}")
	g.P("}")
	g.P()

	for _, method := range service.Methods {
		if !cmdutils.IsUnaryMethod(method) {
			continue
		}
		g.P(formatMethodComment(method.GoName, cmdutils.NormalizeCommentText(method.Comments.Leading)))
		g.P("func (c *", caseName, ") ", bizMethodSignature(g, file, method), " {")
		generateBizMethodBody(g, method)
		g.P("}")
		g.P()
	}
}

// generateUnaryMethodBody 生成一元 RPC 固定模版，统一转调 biz 层 Case。
func generateUnaryMethodBody(g *protogen.GeneratedFile, file *protogen.File, method *protogen.Method, caseFieldName string) {
	errorMessage := strconv.Quote(methodErrorMessage(method))
	wrapInternal := g.QualifiedGoIdent(errorsxImportPath(file).Ident("WrapInternal"))
	if isEmptyReply(method) {
		g.P("err := s.", caseFieldName, ".", method.GoName, "(", serviceCaseArgs(method), ")")
		g.P("if err != nil {")
		g.P(g.QualifiedGoIdent(logPackage.Ident("Error")), "(", strconv.Quote(method.GoName), `, "error", err)`)
		g.P("return nil, ", wrapInternal, "(err, ", errorMessage, ")")
		g.P("}")
		g.P("return new(", goIdent(g, method.Output.GoIdent), "), nil")
		return
	}

	g.P("res, err := s.", caseFieldName, ".", method.GoName, "(", serviceCaseArgs(method), ")")
	g.P("if err != nil {")
	g.P(g.QualifiedGoIdent(logPackage.Ident("Error")), "(", strconv.Quote(method.GoName), `, "error", err)`)
	g.P("return nil, ", wrapInternal, "(err, ", errorMessage, ")")
	g.P("}")
	g.P("return res, nil")
}

// generateBizMethodBody 生成 biz 层固定方法体。
func generateBizMethodBody(g *protogen.GeneratedFile, method *protogen.Method) {
	if isEmptyReply(method) {
		g.P("return nil")
		return
	}

	g.P("// TODO: 在此补充具体业务逻辑。")
	g.P("return &", goIdent(g, method.Output.GoIdent), "{}, nil")
}

// bizFilename 返回 biz 文件输出路径，统一将 service_tmp 目录映射到 service。
func bizFilename(file *protogen.File) string {
	filename := path.Join(path.Dir(file.GeneratedFilenamePrefix), "biz", path.Base(file.GeneratedFilenamePrefix)+".go")
	filename = replacePathSegment(filename, "service_tmp", "service")
	return replacePathSequence(filename, []string{"api", "gen", "go"}, []string{"service"})
}

// bizImportPath 返回 biz 包 import 路径，统一将 service_tmp 包路径映射到 service。
func bizImportPath(file *protogen.File) protogen.GoImportPath {
	importPath := path.Join(string(file.GoImportPath), "biz")
	importPath = replacePathSegment(importPath, "service_tmp", "service")
	importPath = replacePathSequence(importPath, []string{"api", "gen", "go"}, []string{"service"})
	importPath = trimVersionBeforeBiz(importPath)
	return protogen.GoImportPath(importPath)
}

// errorsxImportPath 返回项目统一错误包路径。
func errorsxImportPath(file *protogen.File) protogen.GoImportPath {
	importPath := string(file.GoImportPath)
	index := strings.Index(importPath, "/api/gen/go")
	if index < 0 {
		return protogen.GoImportPath("shop/pkg/errorsx")
	}
	return protogen.GoImportPath(importPath[:index] + "/pkg/errorsx")
}

// goIdent 返回 Go 标识符引用，版本目录包统一使用 appv1/adminv1 等项目真实别名。
func goIdent(g *protogen.GeneratedFile, ident protogen.GoIdent) string {
	importPath := string(ident.GoImportPath)
	if !cmdutils.IsVersionedImportPath(importPath) {
		return g.QualifiedGoIdent(ident)
	}
	g.Import(ident.GoImportPath)
	return cmdutils.DefaultVersionedImportAlias(importPath) + "." + ident.GoName
}

// replacePathSegment 将路径中的指定目录段替换为目标目录段。
func replacePathSegment(source, oldSegment, newSegment string) string {
	parts := strings.Split(source, "/")
	for index, part := range parts {
		if part == oldSegment {
			parts[index] = newSegment
		}
	}
	return strings.Join(parts, "/")
}

// replacePathSequence 将路径中的一段连续目录替换为新的目录序列。
func replacePathSequence(source string, oldSegments, newSegments []string) string {
	parts := strings.Split(source, "/")
	if len(oldSegments) == 0 || len(parts) < len(oldSegments) {
		return source
	}

	for index := 0; index <= len(parts)-len(oldSegments); index++ {
		if !matchesPathSequence(parts[index:index+len(oldSegments)], oldSegments) {
			continue
		}

		var replaced []string
		replaced = append(replaced, parts[:index]...)
		replaced = append(replaced, newSegments...)
		replaced = append(replaced, parts[index+len(oldSegments):]...)
		return strings.Join(replaced, "/")
	}
	return source
}

// trimVersionBeforeBiz 移除 service import path 中 biz 前的 proto 版本目录。
func trimVersionBeforeBiz(source string) string {
	parts := strings.Split(source, "/")
	if len(parts) < 2 || parts[len(parts)-1] != "biz" {
		return source
	}
	versionIndex := len(parts) - 2
	if !cmdutils.IsVersionSegment(parts[versionIndex]) {
		return source
	}
	parts = append(parts[:versionIndex], parts[versionIndex+1:]...)
	return strings.Join(parts, "/")
}

// matchesPathSequence 判断两个路径片段序列是否完全一致。
func matchesPathSequence(parts, targets []string) bool {
	if len(parts) != len(targets) {
		return false
	}
	for index := range parts {
		if parts[index] != targets[index] {
			return false
		}
	}
	return true
}

// formatTypeComment 生成结构体和构造函数注释，统一采用“名称 描述”格式。
func formatTypeComment(name, comment string) string {
	if comment == "" {
		return "// " + name
	}
	if strings.HasPrefix(name, "New") {
		return "// " + name + " 创建" + comment
	}

	return "// " + name + " " + comment
}

// formatMethodComment 生成方法注释，保持“// 方法名 描述”的输出样式。
func formatMethodComment(name, comment string) string {
	if comment == "" {
		return "// " + name
	}
	return "// " + name + " " + comment
}

// serverSignature 生成服务方法签名，统一处理一元与流式 RPC 的参数列表。
func serverSignature(g *protogen.GeneratedFile, method *protogen.Method) string {
	var reqArgs []string
	ret := "error"
	if cmdutils.IsUnaryMethod(method) {
		reqArgs = append(reqArgs, "ctx "+g.QualifiedGoIdent(contextPackage.Ident("Context")))
		ret = "(*" + goIdent(g, method.Output.GoIdent) + ", error)"
	}
	if !method.Desc.IsStreamingClient() {
		reqArgs = append(reqArgs, "req *"+goIdent(g, method.Input.GoIdent))
	}
	if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
		reqArgs = append(reqArgs, "fns api."+method.Parent.GoName+"_"+method.GoName+"Server") //临时这样写
		//reqArgs = append(reqArgs, "fns "+g.QualifiedGoIdent(method.Input.GoIdent.GoImportPath.Ident(method.Parent.GoName+"_"+method.GoName+"Server")))
	}
	return method.GoName + "(" + strings.Join(reqArgs, ", ") + ") " + ret
}

// unaryReplyPrefix 返回一元方法的返回值前缀，保证生成代码返回值顺序正确。
func unaryReplyPrefix(method *protogen.Method) string {
	if cmdutils.IsUnaryMethod(method) {
		return "reply, "
	}
	return ""
}

// bizMethodSignature 生成 biz 层方法签名，按 Empty 入参与出参裁剪参数和返回值。
func bizMethodSignature(g *protogen.GeneratedFile, file *protogen.File, method *protogen.Method) string {
	var reqArgs []string
	reqArgs = append(reqArgs, "ctx "+g.QualifiedGoIdent(contextPackage.Ident("Context")))
	if !isEmptyRequest(method) {
		reqArgs = append(reqArgs, "req *"+goIdent(g, method.Input.GoIdent))
	}

	if isEmptyReply(method) {
		return method.GoName + "(" + strings.Join(reqArgs, ", ") + ") error"
	}
	return method.GoName + "(" + strings.Join(reqArgs, ", ") + ") (*" + goIdent(g, method.Output.GoIdent) + ", error)"
}

// serviceCaseName 返回当前 service 对应的 biz Case 类型名。
func serviceCaseName(service *protogen.Service) string {
	name := strings.TrimSuffix(service.GoName, "Service")
	if name == "" {
		name = service.GoName
	}
	return name + "Case"
}

// serviceRepoName 返回当前 service 对应的 Repo 类型名。
func serviceRepoName(service *protogen.Service) string {
	name := strings.TrimSuffix(service.GoName, "Service")
	if name == "" {
		name = service.GoName
	}
	return name + "Repo"
}

// isEmptyRequest 判断方法入参是否为 google.protobuf.Empty。
func isEmptyRequest(method *protogen.Method) bool {
	return string(method.Input.Desc.FullName()) == "google.protobuf.Empty" || len(method.Input.Fields) == 0
}

// isEmptyReply 判断方法返回值是否为 google.protobuf.Empty。
func isEmptyReply(method *protogen.Method) bool {
	return string(method.Output.Desc.FullName()) == "google.protobuf.Empty"
}

// serviceCaseArgs 返回 service 调用 biz 层时的参数列表。
func serviceCaseArgs(method *protogen.Method) string {
	if isEmptyRequest(method) {
		return "ctx"
	}
	return "ctx, req"
}

// methodErrorMessage 生成固定模版中的中文错误提示。
func methodErrorMessage(method *protogen.Method) string {
	comment := cmdutils.NormalizeCommentText(method.Comments.Leading)
	if comment == "" {
		return method.GoName + "失败"
	}
	return comment + "失败"
}

// genServerMethod 生成底层 gRPC Handler 与流式辅助类型，当前保留供后续扩展复用。
func genServerMethod(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile, method *protogen.Method) string {
	service := method.Parent
	hname := fmt.Sprintf("_%s_%s_Handler", service.GoName, method.GoName)

	if cmdutils.IsUnaryMethod(method) {
		g.P(method.Comments.Leading, "func ", hname, "(srv interface{}, ctx ", contextPackage.Ident("Context"), ", dec func(interface{}) error, interceptor ", grpcPackage.Ident("UnaryServerInterceptor"), ") (interface{}, error) {")
		g.P("in := new(", method.Input.GoIdent, ")")
		g.P("if err := dec(in); err != nil { return nil, err }")
		g.P("if interceptor == nil { return srv.(", service.GoName, "Server).", method.GoName, "(ctx, in) }")
		g.P("info := &", grpcPackage.Ident("UnaryServerInfo"), "{")
		g.P("Server: srv,")
		g.P("FullMethod: ", strconv.Quote(fmt.Sprintf("/%s/%s", service.Desc.FullName(), method.Desc.Name())), ",")
		g.P("}")
		g.P("handler := func(ctx ", contextPackage.Ident("Context"), ", req interface{}) (interface{}, error) {")
		g.P("return srv.(", service.GoName, "Server).", method.GoName, "(ctx, req.(*", method.Input.GoIdent, "))")
		g.P("}")
		g.P("return interceptor(ctx, in, info, handler)")
		g.P("}")
		g.P()
		return hname
	}
	streamType := cmdutils.Unexport(service.GoName) + method.GoName + "Server"
	g.P(method.Comments.Leading, "func ", hname, "(srv interface{}, stream ", grpcPackage.Ident("ServerStream"), ") error {")
	if !method.Desc.IsStreamingClient() {
		g.P("m := new(", method.Input.GoIdent, ")")
		g.P("if err := stream.RecvMsg(m); err != nil { return err }")
		g.P("return srv.(", service.GoName, "Server).", method.GoName, "(m, &", streamType, "{stream})")
	} else {
		g.P("return srv.(", service.GoName, "Server).", method.GoName, "(&", streamType, "{stream})")
	}
	g.P("}")
	g.P()

	genSend := method.Desc.IsStreamingServer()
	genSendAndClose := !method.Desc.IsStreamingServer()
	genRecv := method.Desc.IsStreamingClient()

	// Stream auxiliary types and methods.
	g.P("type ", service.GoName, "_", method.GoName, "Server interface {")
	if genSend {
		g.P("Send(*", method.Output.GoIdent, ") error")
	}
	if genSendAndClose {
		g.P("SendAndClose(*", method.Output.GoIdent, ") error")
	}
	if genRecv {
		g.P("Recv() (*", method.Input.GoIdent, ", error)")
	}
	g.P(grpcPackage.Ident("ServerStream"))
	g.P("}")
	g.P()

	g.P("type ", streamType, " struct {")
	g.P(grpcPackage.Ident("ServerStream"))
	g.P("}")
	g.P()

	if genSend {
		g.P("func (x *", streamType, ") Send(m *", method.Output.GoIdent, ") error {")
		g.P("return x.ServerStream.SendMsg(m)")
		g.P("}")
		g.P()
	}
	if genSendAndClose {
		g.P("func (x *", streamType, ") SendAndClose(m *", method.Output.GoIdent, ") error {")
		g.P("return x.ServerStream.SendMsg(m)")
		g.P("}")
		g.P()
	}
	if genRecv {
		g.P("func (x *", streamType, ") Recv() (*", method.Input.GoIdent, ", error) {")
		g.P("m := new(", method.Input.GoIdent, ")")
		g.P("if err := x.ServerStream.RecvMsg(m); err != nil { return nil, err }")
		g.P("return m, nil")
		g.P("}")
		g.P()
	}
	return hname
}
